name: QA
values:
  - key: base_url
    value: 'https://qa.pro-inspector.net/V4-WCF'
    enabled: true
  - key: token
    value: 584f58b8-ac8e-4136-9dfe-3f44996708d3
    enabled: true
  - key: timing_results
    value: ''
    enabled: true
  - key: t_GetInspections_start
    value: ''
    enabled: true
  - key: t_GetInspections_ms
    value: ''
    enabled: true
  - key: tableCode
    value: ''
    enabled: true
  - key: t_GetDashboardDetails_start
    value: ''
    enabled: true
  - key: t_GetDashboardDetails_ms
    value: ''
    enabled: true
  - key: t_GetSyncTables_start
    value: ''
    enabled: true
  - key: t_GetSyncTables_ms
    value: ''
    enabled: true
  - key: cl_pageSize
    value: ''
    enabled: true
  - key: cl_startIndex
    value: '0'
    enabled: true
  - key: cl_recordCount
    value: ''
    enabled: true
  - key: t_GetChecklistConfiguration_start
    value: ''
    enabled: true
  - key: t_GetChecklistConfiguration_ms
    value: ''
    enabled: true
  - key: checklist_hasFormula
    value: ''
    enabled: true
  - key: checklist_hasInternalTable
    value: ''
    enabled: true
  - key: checklist_parentIds
    value: ''
    enabled: true
  - key: t_GetChecklistFormulaDetails_ms
    value: ''
    enabled: true
  - key: skip_formula
    value: ''
    enabled: true
  - key: t_GetAllInternalTables_ms
    value: ''
    enabled: true
  - key: skip_internalTable
    value: ''
    enabled: true
  - key: t_GetChecklistFormulaDetails_start
    value: ''
    enabled: true
  - key: checklistId
    value: '17'
    enabled: true
  - key: internalTable_parentId
    value: ''
    enabled: true
  - key: t_GetAllInternalTables_start
    value: ''
    enabled: true
  - key: scheduleID
    value: '336312'
    enabled: true
  - key: t_GetExecutionDetails_start
    value: ''
    enabled: true
  - key: t_GetExecutionDetails_ms
    value: ''
    enabled: true
  - key: t_UpdateofflineStatus_start
    value: ''
    enabled: true
  - key: t_UpdateofflineStatus_ms
    value: ''
    enabled: true
color: 0
